on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      - name: Install Hugo
        run: |
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name')
          mkdir tmp/ && cd tmp/
          curl -sSL https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/hugo_extended_${HUGO_VERSION:1}_Linux-64bit.tar.gz | tar -xvzf-
          mv hugo /usr/local/bin/
          cd .. && rm -rf tmp/
          cd ${GITHUB_WORKSPACE}
          hugo version || exit 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:  # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY should be set at repo secrets
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # - name: Create S3 Bucket with Website Configuration
      #   run: |
      #     aws s3api create-bucket \
      #       --bucket primuslearning-github-actions-website \
      #       --region us-east-1

      #     aws s3api put-public-access-block \
      #       --bucket primuslearning-github-actions-website \
      #       --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

      #     aws s3api put-bucket-website \
      #       --bucket primuslearning-github-actions-website \
      #       --website-configuration '{
      #           "IndexDocument": {
      #               "Suffix": "index.html"
      #           },
      #           "ErrorDocument": {
      #               "Key": "error.html"
      #           }
      #       }'

      #     # Add a bucket policy to allow public read access
      #     aws s3api put-bucket-policy \
      #       --bucket primuslearning-github-actions-website \
      #       --policy '{
      #           "Version": "2012-10-17",
      #           "Statement": [
      #               {
      #                   "Effect": "Allow",
      #                   "Principal": "*",
      #                   "Action": "s3:GetObject",
      #                   "Resource": "arn:aws:s3:::primuslearning-github-actions-website/*"
      #               }
      #           ]
      #       }'
            
      - name: Display Website URL
        run: |
          echo "Your website is hosted at http://${{vars.S3_BUCKET_NAME}}.s3-website-us-east-1.amazonaws.com"

      - name: Hugo Build 
        run: |
          cd ${GITHUB_WORKSPACE}
          cd hugo_site_src
          hugo || exit 1

      - name: Deploy static site to S3 bucket # S3_BUCKET_NAME should be set as a repo variable
        run: |
          pwd
          ls
      #    aws s3 sync ./public/ "s3://${{vars.S3_BUCKET_NAME}}" --delete

